version: "3"

services: 
  #ยง data.config.manual.docker.services.frontend.name + ':'
  frontend:
    #ยง 'container_name: ' + data.config.manual.docker.services.frontend.container
    container_name: wise-manual
    #ยง 'image: ' + data.config.manual.docker.services.frontend.image
    image: wise/manual
    build: .
    restart: always
    ports:
      #ยง '- ' + data.config.manual.port + ':4000'
      - 8096:4000
